on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1  check out your repository
      - uses: actions/checkout@v5
      # 2  install the AVR tool-chain
      - name: Install AVR GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr binutils-avr avr-libc simavr
      # 3  compile your C file
      - name: Compile
        run: |
          avr-gcc -mmcu=attiny13a -Os -o stepper.elf main.c
          avr-objcopy -O ihex -R .eeprom stepper.elf stepper.hex
      # 4  run a short simulation
      - name: Simulate firmware
        run: |
          # simavr  -m attiny13 -f 9600000   stepper.elf
      # 5  attach the results to the run
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stepper
          path: |
            stepper.hex
            stepper.elf
